name: WinGet Releaser
description: Publish new releases of your application to Windows Package Manager Community Repository easily.
inputs:
  identifier:
    required: true
    description: The PackageIdentifier of the package you want to release.
  version-regex:
    required: true
    description: The regex to use to extract the version from the tag name.
    default: '[0-9.]+'
  installers-regex:
    required: true
    description: The regex to match the installers.
    default: '.(exe|msi|msix|appx)(bundle){0,1}$'
  delete-previous-version:
    required: true
    description: Whether to delete the last version.
    default: 'false'
  token:
    required: true
    description: GitHub token to create pull request on Windows Package Manager Community Repository.
  fork-user:
    required: true
    description: GitHub username where the fork of winget-pkgs is present.
    default: ${{ github.repository_owner }}
runs:
  using: composite
  steps:
    - name: Check runner OS and workflow trigger event
      run: |
        # Check runner OS and workflow trigger event
        if ($IsWindows -eq $false) {
          throw 'This action is only supported on Windows.'
        }
        if ('${{ github.event_name }}' -ne 'release') {
          throw 'This action is only supported on release event.'
        }
        if ('${{ github.event.action }}' -notin @('released', 'prereleased')) {
          throw 'This action is only supported on released and prereleased event types.'
        }
      shell: pwsh
    - name: Checkout action repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        repository: vedantmgoyal2009/vedantmgoyal2009
    - name: Checkout winget-pkgs repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: winget-pkgs-automation/winget-pkgs
        repository: microsoft/winget-pkgs
        token: ${{ inputs.token }}
    - name: Setup working environment
      run: |
        # Setup working environment
        Install-Module -Name powershell-yaml -Repository PSGallery -Scope CurrentUser -Force # Install powershell-yaml module
        # Set git user name, email and remotes
        git config --local user.name '${{ github.repository_owner }}'
        git config --local user.email '${{ github.event.repository.owner.id }}+${{ github.repository_owner }}@users.noreply.github.com'
        git remote rename origin upstream
        git remote add origin https://github.com/${{ inputs.fork-user }}/winget-pkgs.git
        # Copy YamlCreate to Tools folder and set settings
        Copy-Item -Path ..\..\src\YamlCreate.ps1 -Destination .\YamlCreate.ps1 -Force
        git commit --all -m 'Update YamlCreate.ps1 with InputObject functionality' --quiet
        New-Item -ItemType File -Path "$env:LOCALAPPDATA\YamlCreate\Settings.yaml" -Force | Out-Null
        @'
        TestManifestsInSandbox: never
        SaveToTemporaryFolder: never
        AutoSubmitPRs: always
        ContinueWithExistingPRs: never
        SuppressQuickUpdateWarning: true
        EnableDeveloperOptions: true
        '@ | Set-Content -Path $env:LOCALAPPDATA\YamlCreate\Settings.yaml
      shell: pwsh
      working-directory: winget-pkgs-automation/winget-pkgs/Tools
    - name: Update manifests and publish
      run: |
        # Update manifests and publish
        $WinGetDev = (Resolve-Path -Path ..\..\wingetdev\wingetdev.exe).Path # Set wingetdev.exe path variable
        $PrBody = '### Pull request has been automatically created using 🛫 [WinGet Releaser](https://bittu.eu.org/docs/wr-intro).' # Set pull reuqest body
        . ..\..\src\Functions.ps1 # Import functions
        $Upgrade = [System.Management.Automation.PSObject] @{
          PackageIdentifier = '${{ inputs.identifier }}'
          PackageVersion = ('${{ github.event.release.tag_name }}' | Select-String -Pattern '${{ inputs.version-regex }}').Matches.Value
          InstallerUrls = ($env:RELEASE_ASSETS_JSON | ConvertFrom-Json).ForEach({ if ($_.name -match '${{ inputs.installers-regex }}') { $_.browser_download_url } })
          ReleaseNotesUrl = '${{ github.event.release.html_url }}'
          ReleaseDate = (Get-Date -Date '${{ github.event.release.published_at }}').ToString('yyyy-MM-dd')
        }
        $NoOfTimes = 0
        while ($NoOfTimes -le 6) { # Retry total 5 times, on 6th time, throw that action timed out and finish
            try {
                If ('${{ inputs.delete-previous-version }}' -eq 'false' ? $true : $false) {
                    . .\YamlCreate.ps1 -InputObject $Upgrade # Dot-source the script to get pull request body
                } Else {
                    . .\YamlCreate.ps1 -InputObject $Upgrade -DeletePreviousVersion # Dot-source the script to get pull request body
                }
                break
            } catch {
                If ($NoOfTimes -ne 6 -and $_.Exception.Message -in @('Installer URLs are required', 'Number of InstallerUrls are not equal')) {
                    $NoOfTimes++
                    Write-Output "Retrying to get installer URLs... [$NoOfTimes/5] (next retry after 10 minutes)"
                    Start-Sleep -Seconds 600 # Wait for 10 minutes so we don't hit GitHub API rate limit
                    $Upgrade.InstallerUrls = (Invoke-RestMethod -Uri '${{ github.event.release.assets_url }}').ForEach({ if ($_.name -match '${{ inputs.installers-regex }}') { $_.browser_download_url } })
                } ElseIf ($NoOfTimes -eq 6 -and $_.Exception.Message -in @('Installer URLs are required', 'Number of InstallerUrls are not equal')) {
                    throw @"
        Error: 404_SOME_ASSETS_WERE_NOT_FOUND
        If the release CI is still running, please wait till all artifacts are available and then re-run the job.
        Learn more about this error at: https://bittu.eu.org/docs/wr-notes.
        "@
                } Else {
                    throw $_.Exception.Message
                }
            }
        }
      working-directory: winget-pkgs-automation/winget-pkgs/Tools
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        RELEASE_ASSETS_JSON: ${{ toJSON(github.event.release.assets) }}
branding:
  color: blue
  icon: upload-cloud
